import { useEffect, useRef, useState } from 'react';
import { useInView, useReducedMotion } from 'motion/react';
import { Crown, Activity, ArrowUpRight, Egg } from 'lucide-react';
import { Link } from 'react-router-dom';
import type { Season, Rewards } from '../services/season';
import { isDemo } from '../services/season';
import { Interactive } from './motion/Interactive';
import { Reveal } from './motion/Reveal';
import { Ton } from './Icon';
export function seasonProgress(season: Season, now: number) {return Math.max(0,Math.min(100,(now-Date.parse(season.startsAt))/(Date.parse(season.endsAt)-Date.parse(season.startsAt))*100));}
function Count({value}:{value:number}) {const ref=useRef<HTMLSpanElement>(null);const visible=useInView(ref,{once:true});const reduced=useReducedMotion();const [number,setNumber]=useState(value);
 useEffect(()=>{if(!visible||reduced){setNumber(value);return;}let frame=0;const start=performance.now();const tick=(time:number)=>{const t=Math.min((time-start)/1250,1);setNumber(Math.round(value*(1-Math.pow(1-t,3))));if(t<1)frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[visible,value,reduced]);return <span ref={ref} aria-label={value.toLocaleString('en-US')}>{number.toLocaleString('en-US')}</span>;}
export function SeasonPreview({season,rewards,loading,error,retry}: {season?:Season;rewards?:Rewards;loading:boolean;error?:string;retry:()=>void}) {
 const [now,setNow]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(timer);},[]);
 const remaining=season?Math.max(0,Date.parse(season.endsAt)-now):0;const status=season ? (now>=Date.parse(season.endsAt)?'ended':now<Date.parse(season.startsAt)?'upcoming':season.status) : null;
 return <Reveal className="season-section"><div className="section-kicker"><span>THE CURRENT CHAPTER</span>{isDemo&&<span className="demo-label">DEVELOPMENT PREVIEW · SAMPLE DATA</span>}</div><Interactive className="season-card surface" mode="tilt"><div className="season-top"><Link to="/season" className="season-title" data-cursor="view">{season?.name||'Season overview'}<ArrowUpRight size={20}/></Link>{status&&<span className={`status ${status}`}><i/>{status.toUpperCase()}</span>}<span className="season-time">{loading?'Loading season…':season?(status==='ended'?'Season complete':status==='upcoming'?'Starts '+new Date(season.startsAt).toLocaleDateString('en-US',{month:'short',day:'numeric'}):`Ends in ${Math.floor(remaining/86400000)}d ${Math.floor(remaining/3600000)%24}h`):'Awaiting season announcement'}</span></div><div className="progress-track" role="progressbar" aria-label="Season time elapsed" aria-valuemin={0} aria-valuemax={100} aria-valuenow={season?Math.round(seasonProgress(season,now)):0}><span style={{width:season?`${seasonProgress(season,now)}%`:'0%'}}/></div>{error&&<div className="data-notice" role="status">{error}<button onClick={retry}>Try again ↗</button></div>}</Interactive><div className="metrics">{[{icon:<Egg/>,label:'Total BIRD Points',value:season?.totalBirdPoints!=null?<Count value={season.totalBirdPoints}/>:loading?'…':'—',note:season?.name||'Awaiting data',gold:true},{icon:<Crown/>,label:'Reward pool',value:rewards?.pool!=null?`${rewards.pool.toLocaleString('en-US')} TON`:'TBA',note:'Details to be announced',gold:true},{icon:<Ton/>,label:'Network',value:'TON',note:'Planned onchain rewards'},{icon:<Activity/>,label:'Season status',value:status?.toUpperCase()||'PENDING',note:status==='live'?'The farm is open':'Follow the next chapter'}].map((metric,index)=><Reveal key={metric.label} delay={index*.06}><Interactive className={`metric surface ${metric.label === 'Season status' && status === 'live' ? 'metric-active' : ''}`} mode="tilt"><div className={`metric-icon ${metric.gold?'gold':''}`}>{metric.icon}</div><div><span className="metric-label">{metric.label}</span><strong>{metric.value}</strong><span className="metric-note">{metric.note}</span></div></Interactive></Reveal>)}</div></Reveal>;
}

